import requests

def check_site_accessibility(url):
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            return True, url  # URL is accessible
        else:
            return False, url  # URL is broken
    except requests.RequestException:
        return False, url  # URL is broken

# List of URLs to check (your provided URLs)
site_urls = [
    "http://u19-turnier.ch//wp-content/themes/digital-download/new.php",
    "http://udrzba-okien.sk//wp-admin/maint/about.php",
    "http://ufastyle.com//wp-includes/SimplePie/about.php",
    "http://ultimateworldrecord.com//wp-admin/css/wp-damin.php",
    "http://umibrandperu.com//wp-includes/css/about.php",
    "http://uniconsult-kiel.de//wp-includes/sodium_compat/src/Core32/Curve25519/Ge/Core32.php#admin@123",
    "http://urbanadd.com//wp-content/plugins/download-plugin/wp-access.php#fm_admin",
    "http://ustascriptci.com//wp-includes/certificates/autoload_classmap.php",
    "http://vacuumpump.co.za//wp-pano.php#gyWpLHKN@YZVlYfiI",
    "http://valdaycentr.ru//wp-includes/sodium_compat/src/Core32/Curve25519/Ge/Core32.php#admin@123",
    "http://vallealinstante.com.co//simple.php",
    "http://vapeursdessence.fr//simple.php",
    "http://vasha-rubashka.ru//wp-admin/includes/nav.php#admin@123",
    "https://mariamoon.ist/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://4mtasarim.com/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://mediatransit.com.ng/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://melikebal.av.tr/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://singgahbeli.com.my/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://jarekbrzozowski.com/wp-content/themes/admin.php?taf",
    "https://liric.id/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://freeme.top/wp-content/plugins/WordPressCore/admin.php?taf",
    "https://signalstrading.ae/wp-cron.php",
    "https://buyaznereye.com/wp-xmlmp.php",
    "https://hibaexports.com/wp-cron.php",
    "https://www.rollerbikesports.com/wp-xmlmp.php",
    "https://hefazatshop.com/wp-xmlmp.php",
    "https://hulul.tech/wp-xmlmp.php",
    "https://bengalichoice.com/wp-xmlmp.php",
    "https://fethiyelihkab.com/wp-xmlmp.php",
    "http://innovativefood.gr/wp-cron.php",
    "https://www.bansai.ac.th/wp-xmlmp.php",
    "https://www.as-adv.co.il/wp-xmlmp.php",
    "https://ikman.cheapestlanka.com/wp-xmlmp.php",
    "https://gda.works/wp-xmlmp.php",
    "https://sammacmanor.org/CMS/wp-xmlmp.php",
    "https://bawadikarbala.iq/wp-xmlmp.php",
    "https://mobiletireservicebroward.com/wp-xmlmp.php",
    "https://www.figroup.co.th/jp/wp-xmlmp.php",
    "https://defensorsantiago.gob.ar/wp-xmlmp.php",
    "https://www.zeezautomotives.com/wp-xmlmp.php",
    "https://www.osayazilim.com/wp-xmlmp.php",
    "https://tillastage.wpengine.com/wp-xmlmp.php",
    "https://myc-ci.ajadesarrollo.es/wp-links-opml.php",
    "https://ascosinergitama.com/wp-links-opml.php",
    "https://clasicasdelamor.com/prensa/wp-config-sample.php",
    "http://www.remopt.com/wp-content/wp-configssss.php",
    "https://gauchahotel.com.br/wp-configssss.php",
    "https://gracecare.com.my/wp-config-sample.php",
    "https://ajm555.live/wp-configssss.php",
    "https://pratapersianas.com.br/wp-configssss.php",
    "https://dxit.com.br/wp-configssss.php",
    "https://desarrollo.top/voluntariado/wp-config-sample.php",
    "http://kovinarjoze.com/wp-configsss.php",
    "https://vilasecaonline.com/wp-configssss.php",
    "https://power38th.info/wp-configssss.php",
    "https://www.palemot.gr/wp-config-sample.php",
    "http://taladsai.go.th/wp-config-sample.php",
    "https://dev.sanroque.prodequa.com/wp-config-sample.php",
    "https://eryka.millonariamente.com/wp-config-sample.php",
    "https://apstac.com/rishad/wp-configssss.php",
    "https://pinovaccaro.com/wp-config-sample.php",
    "http://atleticoclubdesocios.es/tienda2/wp-configssss.php",
    "https://maresias.com.br/wp-content/plugins/pluginss/wp-configssss.php?p=",
    "https://egitimortagim.bte.org.tr/wp-configssss.php",
    "https://van-bent.com/wp-configssss.php",
    "https://parroquiasanclemente.cl/wp-config-sample.php",
    "https://academiartisticasomosarte.com/wp-config-sample.php",
    "http://blueoptik.com.tr/wp-configssss.php?p=",
    "https://mazametalurgica.com.br/wp-configssss.php",
    "https://plugin.comprateloen.com/wp-configssss.php",
    "https://atacadaosulmoveis.com.br/wp-content/plugins/pluginss/wp-configssss.php?p=",
    "https://robe.co.il/wp-config-sample.php",
    "https://www.antikohotel.com/wp-configssss.php",
    "https://sangoanhminh.com/wp-configssss.php",
    "https://w3i.com/wp-configssss.php",
    "https://sewingoptimizer.com/wp-configss1.php",
    "https://pulseforhope.co.za/wp-configss1.php",
    "http://zofku.gogler.com.pl/wp-configss1.php",
    "https://5thavenuebuzz.com/wp-configss1.php",
    "https://w105.ws1.wsolution.website/wp-configss1.php",
    "https://newhorizonscs.com.au/wp-configss1.php",
    "https://rebrand-yourself.pl/wp-configss1.php",
    "https://renganathasharma.com/rs/wp-configss1.php",
    "https://www.kaltern-am-see.info/wp-configss1.php",
    "https://www.wprevamp.com/wp/infinity/wp-configss1.php",
    "https://onairstereo.online/wp50/wp-configss1.php",
    "https://lgpdoquefazer.com.br/wp-configss1.php",
    "https://sightfuleye.com/wp-configss1.php",
    "https://event.mentorbisnisdigital.com/wp-configss1.php",
    "https://storedemo.cogzon.com/wp-configss1.php",
    "https://omnutritionist.co.uk/wp-configss1.php",
    "https://unocyber.id/wp-configss1.php",
    "https://serpa.africa/wp-configss1.php",
    "https://canilmrpoms.com.br/wp-configss1.php",
    "https://photoprint.cogzon.org/wp-configss1.php",
    "https://aldin.rosentv.no/wp-configss1.php",
    "https://libraconsultantsug.com/wp-configss1.php",
    "https://staging.mycen.com.my/wp-configss1.php",
    "https://elija.motiv8cloud.com/wp-configss1.php",
    "https://coultershaw.co.uk/wp-configss1.php",
    "https://www.satyajewellers.com/wp-configss1.php",
    "https://appsi.co.id/wp-configss1.php",
    "https://www.kreditvergleich-24.eu/wp-configss1.php",
    "https://seriea.pundit365.com/wp-configss1.php",
    "https://minneapolisairporttaxiservice.com/wp-configss1.php",
    "https://laliga.pundit365.com/wp-configss1.php",
    "https://projstaginglink.com/Emotionally-waxed/wp-configss1.php",
    "https://im.indakmediahosting.com/wp-configss1.php",
    "https://www.essence-gas.com/wp-configss1.php",
    "https://blog.signi.im/wp-configss1.php",
    "https://store.dukanty.com/wp-configss1.php",
    "https://mancity.pundit365.com/wp-configss1.php",
    "https://zealothaulage.com/wp-configss1.php",
    "https://istikana.wp-tricks.net/wp-configss1.php",
    "https://peasconsulting.com/wp-configss1.php",
    "https://softechexperts.com/wp-configss1.php",
    "https://abccomplex.eu/wp-configss1.php",
    "https://lbmelectrical.co.uk/wp-configss1.php",
    "https://webifibra.pixell.cc/wp-configss1.php",
    "https://www.chocotimbers.com.br/wp-configss1.php",
    "https://www.icelandicwonders.is/wp-configss1.php",
    "https://aumpharma.com/wp-configss1.php",
    "https://prosi.myhero.my.id/prodi/wp-configss1.php",
    "https://cricket.pundit365.com/wp-configss1.php",
    "https://itfx.co.za/wp-configss1.php",
    "https://www.news11gujarati.com/wp-configss1.php",
    "https://platiniumgold.com/wp-configss1.php",
    "https://www.mebeldesigns.com/wp-configss1.php",
    "https://flymarathon.innvotech.net/wp-configss1.php",
    "https://smslan.fixcash.se/wp-configss1.php",
    "https://f1.pundit365.com/wp-configss1.php",
    "https://stage.alexabril.eus/wp-content/plugins/nigga/ngif.php",
    "https://marinaplatforms.com/wp-configss1.php",
    "https://hundalconstruction.com/wp-configss1.php",
    "https://meetagreatamerican.com/wp-configss1.php",
    "https://anabeladuarte.pt/Projeto_final/wp-configss1.php",
    "https://build.sellreallikes.com/wp-configss1.php",
    "http://clockpt-serverstaging.theservtech.com/wp-configss1.php",
    "https://putrajaya.kedaiphone.com/wp-configss1.php",
    "https://sahil-alkhaleej.com/wp-configss.php",
    "https://news.finematrix.com/wp-configss1.php",
    "https://www.%E0%B8%93%E0%B8%B1%E0%B8%90%E0%B8%9E%E0%B8%A5%E0%B9%84%E0%B8%A3%E0%B9%88%E0%B8%AB%E0%B8%8D%E0%B9%89%E0%B8%B2.com/wp-configss1.php",
    "https://geonet.me/wp-configss1.php",
    "https://www.sistelingenieria.cl/wp-configss1.php",
    "https://tornoymetalmecanica.com/wp-configss1.php",
    "https://shop.lollipopfactory.eu/wp-configss1.php",
    "https://www.diyabetdanismanim.com/wp-configss1.php",
    "https://universityofportharcourt.com/wp-configss1.php",
    "https://ma.tsm-solvertm.com/wp-configss1.php",
    "http://ftbk.cn/wp-content/plugins/nigga/ngif.php",
    "https://demo.olivelimited.com/wp-configss1.php",
    "https://engineershelper.com/wp-configss1.php",
    "https://www.ynotdesign.in/portfolio/wp-configss1.php",
    "https://feedthecow.in/wp-configss1.php",
    "https://pg333xs.com/wp-configss1.php",
    "https://www.credentials.ogilvy.md/wp-configss1.php",
    "https://pcstore.com.pk/wp-configss1.php",
    "https://sudcompu.net/sediglimpio/wp-configss1.php",
    "https://www.sakonnakhonguide.com/wp-configss1.php",
    "https://pomoze.pl/wp-configss1.php",
    "https://nieuwmolen.com/wp-configss1.php",
    "https://kalambagame.co/wp-configss1.php",
    "http://www.autoserwis.gda.pl/wp-configss1.php",
    "https://jaojengvipx.com/wp-configss1.php",
    "https://forms.assurym.fr/wp-configss1.php",
    "https://lion888.biz/wp-configss1.php",
    "https://quosfavor.quosmarket.com/wp-configss1.php",
    "https://www.kasabankosu.com/wp-configss1.php",
    "https://www.ercillerhaliyikama.com/wp-configss1.php",
    "https://ufabet1212pro.info/wp-configss1.php",
    "https://eng.vitalkimya.com/wp-configss1.php",
    "https://ireneaivar.online/wp-configss1.php",
    "https://ufax789.vip/wp-configss1.php",
    "https://www.mavimet.com.tr/wp-configss1.php",
    "http://www.eftalyadiving.com/wp-configss1.php",
    "https://wm789v1.info/wp-configss1.php",
    "https://ufa333m.pro/wp-configss1.php",
    "http://www.eminevimanaokulu.com/wp-configss1.php",
    "https://aprendepress.com/bodymind-demoweb/wp-configss1.php",
    "https://www.rxroadrunner.com/wp-configss1.php",
    "https://klarotecnologia.com.co/wp-configss1.php",
    "https://drarodriguez.cl/wp-configss1.php",
    "https://ktvvip888k.biz/wp-configss1.php",
    "https://russianescortsinbangalore.com/blog/wp-configss1.php",
    "https://pussybat.com/wp-configss1.php",
    "https://power99.pro/wp-configss1.php",
    "https://dnpgcollege.ac.in/wp-configss1.php",
    "https://taokaebet555.vip/wp-configss1.php",
    "https://studio-legale-raimondi.it/wp-configss1.php",
    "https://professordomtop.com/wp-configss1.php",
    "https://www.mapresse.ma/wp-configss1.php",
    "https://pdm.gologonow.website/wp-content/plugins/nigga/ngif.php",
    "https://cable2.gologonow.website/wp-content/plugins/nigga/ngif.php",
    "https://perfume.gologonow.website/wp-content/plugins/nigga/ngif.php",
    "https://www.turkteavun.com/wp-configss1.php",
    "https://vuayenviet.com.vn/wp-configss1.php",
    "https://royalfacilities.gologonow.website/wp-content/plugins/nigga/ngif.php",
    "https://sabibroker.com/wp-configss1.php",
    "https://pg8gvip.com/wp-configss1.php",
    "https://thecomicsconnection.com/wp-configss.php",
    "https://upgrade.reneengamau.com/wp-configss.php",
    "https://allamericasdistribution.com/wp-configss.php",
    "https://dev.wordpress-developer.us/live-pros/wp-configss1.php",
    "https://www.sewalaptopdibali.com/wp-configss.php",
    "https://metodosuv.com/wp-configss.php",
    "https://triadjapan.gologonow.website/wp-configss.php",
    "https://www.zanshin.ro/wp-configss.php",
    "https://agbatalha.pt/matildeclemente/wp-configss.php",
    "https://liveprojects.co.in/satryna/wp-configss.php",
    "https://lumber.pt/wp-configss.php",
    "http://magaza.highwaycustomgarage.com/wp-configss.php",
    "https://vlgym.gologonow.website/wp-configss.php",
    "https://www.eijotradingplc.com/wp-content/plugins/nigga/ngif.php",
    "https://rebound-zone.com/wp-configss.php",
    "https://vlgym.gologonow.website/wp-configss1.php",
    "https://pdcitycouncil.gologonow.website/wp-content/plugins/nigga/ngif.php",
    "https://gizayperde.com/wp-configss.php",
    "https://ezybet789.online/wp-configss1.php",
    "https://www.fishmatefood.com/wp-configss.php",
    "https://bloodline.gologonow.website/wp-content/plugins/nigga/ngif.php",
    "https://www.cezayirkargo.com/wp-configss.php",
    "https://homeidfurniture.com/wp-content/plugins/nigga/ngif.php",
    "https://hotelimperial.uy/inicio/wp-configss.php",
    "https://icreativeagency.com/ccl-full/wp-configss.php",
    "https://itgcleancarwash.com/wp-configss.php",
    "https://www.koratphotographer.com/wp-content/plugins/nigga/ngif.php",
    "https://knusbd.org/wp-content/plugins/nigga/ngif.php",
    "https://mesamaleta.com/wp-configss.php",
    "https://mmw-erc.com/tester/wordpress/wp-content/plugins/nigga/ngif.php",
    "https://royalestatesl.com/wp-configss.php",
    "https://webapi.ramialali.com/wp-configss.php",
    "https://me-hey569.com/wp-configss.php",
    "https://udicentroautomotivo.com.br/wp-configss1.php",
    "http://dieuhoaminhphong.com//wp-content/themes/cay-van-phong/tinyfilemanager.php#user@12345",
    "http://nordfox.pl//wp-content/themes/digital-download/new.php",
    "http://amazonaviationservice.com//wp-content/themes/digital-download/new.php",
    "http://atasunnakliyat.com.tr//wp-content/themes/cay-van-phong/tinyfilemanager.php#user@12345",
    "http://vidnoeinform.ru//wp-admin/includes/nav.php#admin@123",
    "http://vimaimpex.com//wp-admin/includes/nav.php#admin@123",
    "http://mto.adventistas.org//wp-admin/includes/nav.php#admin@123",
    "http://griffinfence.com//wp-content/plugins/download-plugin/wp-access.php#fm_admin",
    "http://academiaspeaking.es//wp-content/themes/digital-download/new.php",
    "http://utika.ru//wp-content/themes/digital-download/new.php",
    "http://simplicon.net//wp-content/plugins/download-plugin/wp-access.php#fm_admin",
    "http://jp-renov-pau.fr//wp-content/themes/digital-download/new.php",
    "http://nasza-rzeka.pl//wp-content/themes/digital-download/new.php",
    "http://ligeia.eu//wp-content/plugins/simple/simple.php"
]

# Lists to store results
accessible_urls = []
broken_urls = []

# Check accessibility of each URL
for url in site_urls:
    is_accessible, url = check_site_accessibility(url)
    if is_accessible:
        accessible_urls.append(url)
    else:
        broken_urls.append(url)

# Display results
print("=== ACCESSIBLE URLs ===")
for url in accessible_urls:
    print(f"OK {url} ✅")

print("\n=== BROKEN URLs ===")
for url in broken_urls:
    print(f"BROKEN {url} ❌")
